CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    email                VARCHAR(255)                            NOT NULL,
    password             VARCHAR(255)                            NOT NULL,
    role                 VARCHAR(255)                            NOT NULL,
    email_verified       BOOLEAN                                 NOT NULL,
    verification_token   VARCHAR(255),
    reset_password_token VARCHAR(255),
    reset_token_expiry   TIMESTAMP WITHOUT TIME ZONE,
    onboarding_completed BOOLEAN                                 NOT NULL,
    enabled              BOOLEAN                                 NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);