spring.datasource.url=jdbc:postgresql://localhost:5432/nti_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=88863346aec895
spring.mail.password=f7a11310bd511f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true